import { computeStats, type StatsReport } from "./stats.js";
import { sparkline } from "../dashboard/sparkline.js";
import { bucketCounts } from "../dashboard/series.js";
import { formatDuration } from "../analysis/gaps.js";

export interface ReportOptions {
  level?: string;
  since?: string;
  top?: string;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

const CSS = `
body{font-family:ui-monospace,Menlo,monospace;max-width:900px;margin:2rem auto;padding:0 1rem;color:#1a1a2e;background:#fafafa}
h1{border-bottom:2px solid #e2e2ee;padding-bottom:.5rem}
.cards{display:flex;gap:1rem;flex-wrap:wrap;margin:1rem 0}
.card{border:1px solid #d8d8ea;border-radius:8px;padding:.75rem 1.25rem;text-align:center}
.card .n{font-size:1.6rem;font-weight:700}
.card.err .n{color:#c0392b}.card.warn .n{color:#b7950b}.card.info .n{color:#2471a3}
table{border-collapse:collapse;width:100%;margin:.5rem 0 1.5rem}
th,td{text-align:left;border-bottom:1px solid #e6e6f0;padding:.45rem .6rem}
th{color:#666a8f;font-weight:600;font-size:.85rem}
.spark{font-size:11px;letter-spacing:1px;color:#c0392b;word-break:break-all}
.meta{color:#8888a6;font-size:.85rem}
`;

/** Build a self-contained HTML report (inline CSS + SVG sparkline). */
export function renderHtmlReport(title: string, report: StatsReport): string {
  const e = escapeHtml;
  const errorRate =
    report.totalLines > 0 ? ((report.levels.ERROR / report.totalLines) * 100).toFixed(1) : "0.0";

  const rows = report.topGroups
    .map(
      (g, i) =>
        `<tr><td>${i + 1}</td><td class="lvl ${g.level.toLowerCase()}">${g.level}</td>` +
        `<td>${g.count}</td><td>${e(g.sample)}</td>` +
        `<td class="meta">${g.firstSeen ?? "?"} → ${g.lastSeen ?? "?"}</td></tr>`,
    )
    .join("\n");

  // Sparkline over the covered range.
  const first = report.timeRange.first ? Date.parse(report.timeRange.first) : null;
  const last = report.timeRange.last ? Date.parse(report.timeRange.last) : null;
  const chart =
    first !== null && last !== null
      ? sparkline(bucketCounts([first, last], first, last, 40), 40)
      : "";

  return `<!doctype html>
<html><head><meta charset="utf-8"><title>logscope — ${e(title)}</title><style>${CSS}</style></head>
<body>
<h1>logscope report — ${e(title)}</h1>
<div class="cards">
  <div class="card"><div class="n">${report.totalLines}</div>lines</div>
  <div class="card err"><div class="n">${report.levels.ERROR}</div>errors (${errorRate}%)</div>
  <div class="card warn"><div class="n">${report.levels.WARN}</div>warnings</div>
  <div class="card info"><div class="n">${report.levels.INFO}</div>info</div>
  <div class="card"><div class="n">${report.unparsedLines}</div>unparsed</div>
</div>
<p class="meta">time range: ${report.timeRange.first ?? "?"} → ${report.timeRange.last ?? "?"}</p>
<h2>rate over time</h2>
<p class="spark">${chart || "—"}</p>
<h2>top message groups</h2>
<table>
<tr><th>#</th><th>level</th><th>count</th><th>sample</th><th>seen</th></tr>
${rows || '<tr><td colspan="5" class="meta">no entries</td></tr>'}
</table>
<p class="meta">generated by logscope · ${new Date().toISOString()}</p>
</body></html>`;
}

/** Markdown variant suitable for GitHub issue bodies. */
export function renderMarkdownReport(title: string, report: StatsReport): string {
  const lines: string[] = [
    `# logscope report — ${title}`,
    "",
    `**${report.totalLines}** lines · **${report.levels.ERROR}** errors · ` +
      `**${report.levels.WARN}** warnings · **${report.levels.INFO}** info · ` +
      `${report.unparsedLines} unparsed`,
    "",
    `- time range: \`${report.timeRange.first ?? "?"}\` → \`${report.timeRange.last ?? "?"}\``,
    "",
    "| # | level | count | sample | seen |",
    "|---|-------|-------|--------|------|",
  ];
  report.topGroups.forEach((g, i) => {
    lines.push(
      `| ${i + 1} | ${g.level} | ${g.count} | ${g.sample.replace(/\|/g, "\\|")} | ` +
        `${g.firstSeen ?? "?"} → ${g.lastSeen ?? "?"} |`,
    );
  });
  lines.push("", `_generated by logscope_`);
  return lines.join("\n") + "\n";
}

export { computeStats };
